apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: sonarqube-template-test
  title: Sonarqube Template Test
  description: A test to see if we can create a workflow in GitHub from Backstage template
spec:
  owner: Scott Broersma
  type: service

  parameters:
    - title: Fill in some steps
      properties:
        url:
          title: Source url
          type: string
          ui:field: RepoUrlPicker
        targetPath:
          title: Target Path
          type: string

  steps:
    - id: fetch-docs
      name: Fetch Docs
      action: fetch:plain
      input:
        targetPath: ${{ parameters.url }}
        url: ${{ parameters.targetPath }}
