apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: sonarqube-template-test
  title: Sonarqube Template Test
  description: A test to see if we can create a workflow in GitHub from Backstage template
spec:
  owner: Scott Broersma
  type: service

  steps:
    - id: fetch-docs
        name: Fetch Docs
        action: fetch:plain
        input:
          targetPath: ./github_actions.yaml
          url: https://github.com/sbroersma/hello_world_template
