apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: sonarqube-template-test
  title: Sonarqube Template Test
  description: A test to see if we can create a workflow in GitHub from Backstage template
spec:
  #owner: Scott Broersma
  type: service

  parameters:
    - title: Fill in some steps
      properties:
        url:
          title: Source url
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
        targetPath:
          title: Target Path
          type: string
        
        

  steps:
    - id: fetch-docs
      name: Fetch Docs
      action: fetch:plain
      input:
        owner: "sbroersma"
        targetPath: ${{ parameters.targetPath }}
        url: ${{ parameters.url }}
    - id: output_workspace
      name: Output workspace
      action: debug:log
      input:
        message: $ {{ pwd }}
        listWorkspace: True



   
